# Generated by Django 4.0.3 on 2022-03-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_mr_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mr_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
