# Generated by Django 4.0.3 on 2022-03-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_dr_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dr_user',
            name='dr_fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visit',
            name='remark',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
