# Generated by Django 4.0.3 on 2022-03-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_dr_user_dr_fullname_visit_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='doctor_name',
            new_name='doctor_first_name',
        ),
        migrations.RemoveField(
            model_name='dr_user',
            name='dr_fullname',
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor_last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
