# Generated by Django 4.0.3 on 2022-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_doctor_name_visit_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ppt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('ppt_slides', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='mr_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='mr_longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dr_user',
            name='profile_pic',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
