# Generated by Django 3.1.2 on 2022-04-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20220328_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
