# Generated by Django 3.1.2 on 2022-04-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_slide_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='url',
            new_name='slide_url',
        ),
    ]
