# Generated by Django 3.1.2 on 2022-04-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20220407_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='slide_url',
        ),
    ]
